

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: docker-aws
  env: DockerAws-env
  bucket_name: elasticbeanstalk-ap-south-1-920033848866
  bucket_path: cloth-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY